# Ultralytics YOLO ğŸš€, AGPL-3.0 license
# YOLOv8-seg instance segmentation model. For Usage examples see https://docs.ultralytics.com/tasks/segment

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-seg.yaml' will call yolov8-seg.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]
# depth_multiple: 0.33  # model depth multiple æ§åˆ¶æ¨¡å‹çš„æ·±åº¦ï¼Œä»…åœ¨repeats>1æ—¶æœ‰æ•ˆ
# width_multiple: 0.25  # model width multiple æ§åˆ¶æ¨¡å‹çš„å®½åº¦ï¼Œä¸»è¦ä½œç”¨äºargsä¸­çš„ch_outå‚æ•°ï¼ˆç¬¬ä¸€ä¸ªï¼‰
# å¦‚ç¬¬ä¸€ä¸ªConvå±‚ï¼Œch_out=64ï¼Œé‚£ä¹ˆåœ¨v8nå®é™…è¿ç®—è¿‡ç¨‹ä¸­ï¼Œä¼šå°†å·ç§¯è¿‡ç¨‹ä¸­çš„å·ç§¯æ ¸è®¾ä¸º64x0.25ï¼Œæ‰€ä»¥ä¼šè¾“å‡º16é€šé“çš„ç‰¹å¾å›¾ã€‚
# ç¬¬ä¸‰å±‚é‡å¤ä¸‰æ¬¡ï¼Œå®é™…æ¬¡æ•°ä¹˜depthï¼Œn=3*d=3*0.33=1ï¼Œæ‰€ä»¥å®é™…ä¸Šåªä¼šé‡å¤ä¸€æ¬¡ï¼Œå³yolov8nåªæœ‰ä¸€æ¬¡C3fæ“ä½œã€‚

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]                     # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]                    # 1-P2/4
  - [-1, 3, C2f, [128, True]]                     # 2
  - [-2, 3, MFACB, [128, 3, 1, [2, 2, 2]]]        # 3
  - [[-1, -2], 1, Concat, [1]]                    # 4
  - [-1, 1, DepthwiseSeparableConv, [128]]  # 5
  - [-1, 1, Conv, [256, 3, 2]]                    # 6-P3/8
  - [-1, 6, C2f, [256, True]]                     # 7
  - [-1, 1, Conv, [512, 3, 2]]                    # 8-P4/16
  - [-1, 6, C2f, [512, True]]                     # 9
  - [-1, 1, Conv, [1024, 3, 2]]                   # 10-P5/32
  - [-1, 3, C2f, [1024, True]]                    # 11
  - [-1, 1, SPPF, [1024, 5]]                      # 12

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]   # 13
  - [[-1, 9], 1, Concat, [1]]                    # 14 cat backbone P4
  - [-1, 3, C2f, [512]]                          # 15

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]   # 16
  - [[-1, 7], 1, Concat, [1]]                    # 17 cat backbone P3
  - [-1, 3, C2f, [256]]                          # 18 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]                   # 19
  - [[-1, 15], 1, Concat, [1]]                   # 20 cat head P4
  - [-1, 3, C2f, [512]]                          # 21 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]                   # 22
  - [[-1, 12], 1, Concat, [1]]                    # 23 cat head P5
  - [-1, 3, C2f, [1024]]                         # 24 (P5/32-large)

  - [[18, 21, 24], 1, Segment, [nc, 32, 256]] # Segment(P3, P4, P5)
